### ISSUE TITLE
Moving JWST to github

### ISSUE THREAD

**Issue by nden** [spacetelescope/braindump#4]
May 19th, noon, S322

A suggested list of topics to discuss. Please add other topics as you see necessary.
- What to move from SVN to github (we don't have to move everything)
- How to organise the code 
  
  The current organization uses namespaces. IIRC this was necessary because of a requirement that
  steps are to be installed as a separate packages as well as as one package. Is this still a good idea?
- What is the current nightly SSBDEV procedure, i.e. after the code is moved to github what should we 
  expect from the build scripts?
- What workflow to adopt?
  
  [Confluence notes](https://confluence.stsci.edu/display/SSB/Github+and+You)
  
  [astropy](http://astropy.readthedocs.io/en/latest/development/workflow/maintainer_workflow.html)
- Testing
- Documentation
- Releases

**Comment by nden** [comment]
May 19th, noon, S322

**Comment by cdsontag** [comment]
I'll be away for this, but am interested.  Any chance the notes could be posted?

**Comment by nden** [comment]
Yes, I'll post notes here.

**Comment by nden** [comment]
Updated the original issue with suggested agenda for tomorrow's meeting.

**Comment by pllim** [comment]
Very interesting topic but unfortunately I cannot attend. Looking forward to the meeting notes.

Personally:
* :-1: on namespace. Realistically, what user will only ever need a single step? As a user, I'd rather get everything as a single package, which will not cause dependency mismatch problem.
* Both workflows are similar. But Astropy is a bit more complete, I think. I might be biased because I am used to Astropy already. Perhaps a compromise is to start with Joe's workflow, and then adopt Astropy's when everyone is familiar with `git` and GitHub?
* Where are the documents anyway? Please don't say Confluence or SOCCER.

**Comment by nden** [comment]
I added notes from yesterday's meeting. 

https://github.com/spacetelescope/braindump/blob/master/move_to_github_%234/notes-move-to-github.rst

Feel free to add, modify, agree or disagree.

If there's consensus, we may have a sprint next week to reorganize the code, write tests or just mess with github.
